In [1]:
import numpy as np
import pandas as pd

In [3]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:

time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:

date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:

time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### working with date

In [8]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:

date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB


1. Extract year

In [10]:
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
107 2018-12-29        1225       13      60       2018
996 2018-12-06        5521        7       1       2018
699 2018-10-06        1160       13       6       2018
930 2018-09-06        6716       16       4       2018
327 2019-03-26        6115       22      63       2019

2. Extract Month

In [11]:
date['date_month_no']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
707 2019-07-06        2247       16       9       2019              7
801 2018-12-17         630       10      12       2018             12
567 2019-11-15        2457        3      24       2019             11
747 2018-08-06        2490        7       9       2018              8
908 2019-01-20        7510       16       2       2019              1

In [12]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January


Extract Days

In [13]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [14]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [15]:

# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [16]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

Extract week of the year

In [19]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

Extract Quarter

In [20]:

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

Extract Semester

In [21]:

date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1


Extract Time elapsed between dates

In [22]:

import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 14, 10, 34, 22, 515846)

In [23]:

today - date['date']

0     2317 days 10:34:22.515846
1     2799 days 10:34:22.515846
2     2730 days 10:34:22.515846
3     2432 days 10:34:22.515846
4     2655 days 10:34:22.515846
                 ...
995   2745 days 10:34:22.515846
996   2686 days 10:34:22.515846
997   2534 days 10:34:22.515846
998   2599 days 10:34:22.515846
999   2373 days 10:34:22.515846
Name: date, Length: 1000, dtype: timedelta64[ns]

In [24]:
(today - date['date']).dt.days

0      2317
1      2799
2      2730
3      2432
4      2655
       ...
995    2745
996    2686
997    2534
998    2599
999    2373
Name: date, Length: 1000, dtype: int64

In [26]:
# Months passed (exact calculation)
# Convert both 'today' and the 'date' column to Period objects with monthly frequency
months_passed = (pd.Timestamp(today).to_period('M') - date['date'].dt.to_period('M')).apply(lambda x: x.n)
months_passed

0      76
1      92
2      90
3      80
4      87
       ..
995    90
996    88
997    83
998    85
999    78
Name: date, Length: 1000, dtype: int64

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [28]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [29]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time part

In [31]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [32]:
today - time['date']

0     4503 days 09:44:22.515846
1     4367 days 10:54:22.515846
2     4853 days 10:13:22.515846
3     4155 days 10:03:22.515846
4     4552 days 11:23:22.515846
                 ...
995   5142 days 09:44:22.515846
996   4463 days 11:20:22.515846
997   4928 days 10:57:22.515846
998   5044 days 11:00:22.515846
999   4316 days 11:09:22.515846
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.890943e+08
1      3.773481e+08
2      4.193360e+08
3      3.590282e+08
4      3.933338e+08
           ...
995    4.443039e+08
996    3.856440e+08
997    4.258186e+08
998    4.358412e+08
999    3.729426e+08
Name: date, Length: 1000, dtype: float64

In [34]:

# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.484904e+06
1      6.289134e+06
2      6.988933e+06
3      5.983803e+06
4      6.555563e+06
           ...
995    7.405064e+06
996    6.427400e+06
997    7.096977e+06
998    7.264020e+06
999    6.215709e+06
Name: date, Length: 1000, dtype: float64

In [35]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108081.739588
1      104818.906254
2      116482.222921
3       99730.056254
4      109259.389588
           ...
995    123417.739588
996    107123.339588
997    118282.956254
998    121067.006254
999    103595.156254
Name: date, Length: 1000, dtype: float64